### ISSUE TITLE
Multiple mesh IP addresses in luci theme header

### ISSUE THREAD

**Issue by glamrock** [opentechinstitute/luci-commotion#120]
Currently, the header detects the first radio that is up/meshed and displays its IP address:

![screenshot from 2013-12-05 15 17 32](https://f.cloud.github.com/assets/452041/1686643/4c9659e6-5dea-11e3-9bc2-d41d41062d75.png)

However, while we support multiple interfaces meshed at once, this support does not extend to the header display.  We should either add a new page that displays them all, and/or have them all visible in the header (either as a collapsible section, dropdown, or an extra section).

cc @critzo @georgiamoon @elationfoundation

**Comment by jheretic** [comment]
Resolved (at least for specific use cases) by #413. #457 and #458 will be relevant in the future.
