### ISSUE TITLE
Utilize OpenWrt's 'auto-refresh' feature in the luci-commotion framework

### ISSUE THREAD

**Issue by critzo** [opentechinstitute/luci-commotion#162]
This issue was originally submitted to the Commotion website by @andygunn in post-testing of the 1.0 release.

OpenWRT has a feature that displays a button labeled "Auto-Refresh On", which is included in the luci-commotion Status page, but does not provide useful or expected information in the context of a Commotion node. For example, expected behavior in this report was that "Auto-Refresh On" meant that the list of "Nearby Mesh Devices" or their ETX values would be automatically updated.

**Comment by jheretic** [comment]
Implemented by #450
