### ISSUE TITLE
Display wireless signal strength in the Nearby Mesh Devices table

### ISSUE THREAD

**Issue by critzo** [opentechinstitute/luci-commotion#163]
This issue was originally submitted to the Commotion website by @andygunn in post-testing of the 1.0 release.

Viewing the "Status" page in the Administrator interface, there is no indication of wireless signal strength in the neighbors table under "Nearby Mesh Devices".

End user expects to see wireless signal strength indicated in the table of wireless neighbors.

The column and data for wireless signal strength is not yet implemented.

**Comment by jheretic** [comment]
Implemented by #450
