### ISSUE TITLE
Theme optimization

### ISSUE THREAD

**Issue by oti-tech** [opentechinstitute/luci-commotion#288]
<a href="https://github.com/glamrock"><img src="https://avatars.githubusercontent.com/u/452041?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [glamrock](https://github.com/glamrock)**
_Monday May 19, 2014 at 16:36 GMT_
_Originally opened as https://github.com/opentechinstitute/luci-theme-commotion/pull/39_

----

This is still in-progress, but went from ~3000 lines of CSS to ~1900 lines of CSS.  Wanted to merge these changes before getting heavy into theme logic or adding items to the sidebar.

----

_**[glamrock](https://github.com/glamrock)** included the following code: https://github.com/opentechinstitute/luci-theme-commotion/pull/39/commits_

**Comment by jheretic** [comment]
Resolved by #402
