### ISSUE TITLE
DNS spoofing

### ISSUE THREAD

**Issue by oti-tech** [opentechinstitute/luci-commotion#294]
<a href="https://github.com/dismantl"><img src="https://avatars.githubusercontent.com/u/2007008?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dismantl](https://github.com/dismantl)**
_Friday Sep 13, 2013 at 18:44 GMT_
_Originally opened as https://github.com/opentechinstitute/luci-commotion-splash/issues/4_

----

re-try the DNS spoofing feature, but with a script that auto-detects internet connectivity and configures settings.

**Comment by jheretic** [comment]
Implemented per #460
