### ISSUE TITLE
Add country code selector to Setup Wizard

### ISSUE THREAD

**Issue by andygunn** [opentechinstitute/luci-commotion#447]
There should be an option to set what country you are in so the appropriate wireless channels are available. This affects 2.4GHz and 5GHz bands, so it should happen early on.

Also, I'm not sure on the regulations for this, but there should be a "least restrictive" option as well, that opens up all of the available channels the hardware can support, for testing.

It should be present in the current OpenWRT system somewhere, as this is something folks are more or less required to set. It should look something like:

What country is this network operating in?
[Pulldown menu]

**Comment by gradyoti** [comment]
See https://github.com/opentechinstitute/luci-commotion/pull/451

To test:
Run through setup wizard on a single radio and then a multiple radio device. Should be able to set the country for each radio independently.

**Comment by jheretic** [comment]
Addressed by #451
